version: "2.1"
orbs:
  node: circleci/node@5.1.0
workflows:
  auto-attedance:
    jobs:
      - exec-script
jobs:
  exec-script:
    executor:
      name: node/default
      tag: 16.20-browsers
    steps:
      - checkout
      - node/run:
          npm-run: exec
      - run:
          command: zip -r snapshot.zip snapshot
          name: Archiving snapshot
      - store_artifacts:
          path: ./snapshot.zip
