name: Auto attedance

on:
  workflow_dispatch:
    inputs:
      attedance_id:
        description: "Attedance ID"
        required: true
jobs:
  attendance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Run auto attedance
        run: |
          npm ci
          node attedance.js ${{ inputs.attedance_id }}
        env:
          CI: true
          SPADA_USERNAME: ${{ secrets.SPADA_USERNAME }}
          SPADA_PASSWORD: ${{ secrets.SPADA_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTROL_ISSUE_ID: ${{ vars.CONTROL_ISSUE_ID }}
      - name: Archiving Snapshot
        run: |
          cd snapshot
          zip -r -P "${{ secrets.SPADA_USERNAME }}:${{ secrets.SPADA_PASSWORD }}" ../snapshot.zip ./*
      - name: Upload snapshot
        uses: actions/upload-artifact@v4
        with:
          name: snapshot.zip
          path: snapshot.zip
