name: Auto attedance

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Run auto attedance
        run: |
          npm ci
          node main.js
        env:
          CI: true
          SPADA_USERNAME: ${{ secrets.SpadaUsername }}
          SPADA_PASSWORD: ${{ secrets.SpadaPassword }}

